name: Deploy
on: 
  push:
    branches: [ "main" ]
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      HOST: 86.106.181.150
      USERNAME: root
      DIR_NAME: tg_dribbble_promo
      SERVICE_NAME: tg_dribbble_promo
      GITHUB_PATH: git@github.com:AlexStinky/tg_dribbble_promo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /opt/${{ env.DIR_NAME }}
          git pull origin main
          rm -r node_modules
          rm -r package-lock.json
          npm install
          systemctl daemon-reload
          systemctl enable ${{ env.SERVICE_NAME }}
          systemctl stop ${{ env.SERVICE_NAME }}
          systemctl start ${{ env.SERVICE_NAME }}